In [1]:
from typing import List

# MaxSumSubArray

In [ ]:
# 给定一个整数数组 n ，找到一个具有最大和的连续子数组（子数组最少包含一个元素），返回其最大和
# 输入：[-2,1,-3,4,-1,2,1,-5,4]
# 输出：6
# 解释：连续子数组 [4,-1,2,1] 的和最大，为 6

## dp

In [3]:
class Solution:
    def MaxSumSubArray(self, n: List[int]) -> int:
        size = len(n)
        if size == 0:
            raise ValueError
        else:
            x = n[0]
            y = x
            if size > 1:
                for i in range(1, size):
                    x = max(n[i], x+n[i])
                    y = max(x, y)
        return y

In [4]:
n = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
s = Solution()
s.MaxSumSubArray(n)

6

In [ ]:
# 时间复杂度：O(N)
# 空间复杂度：O(1)

## dp with subarray export

In [163]:
class Solution:
    def MaxSumSubArray(self, n: List[int]) -> int:
        size = len(n)
        if size == 0:
            raise ValueError
        else:
            x = n[0]
            y = x
            p = [n[0]]
            q = p.copy()
            if size > 1:
                for i in range(1, size):
                    if x >= 0:
                        x = x+n[i]
                        p.append(n[i])
                    else:
                        x = n[i]
                        p = [n[i]]
                    if x >= y:
                        y = x
                        q = p.copy()
        return y, q

In [164]:
n = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
s = Solution()
s.MaxSumSubArray(n)

(6, [4, -1, 2, 1])

## divide and conquer

In [ ]:
# class Solution:
#     def maxSubArray(self, nums: List[int]) -> int:
#         n = len(nums)
#         #递归终止条件
#         if n == 1:
#             return nums[0]
#         else:
#             #递归计算左半边最大子序和
#             max_left = self.maxSubArray(nums[0:len(nums) // 2])
#             #递归计算右半边最大子序和
#             max_right = self.maxSubArray(nums[len(nums) // 2:len(nums)])
        
#         #计算中间的最大子序和，从右到左计算左边的最大子序和，从左到右计算右边的最大子序和，再相加
#         max_l = nums[len(nums) // 2 - 1]
#         tmp = 0
#         for i in range(len(nums) // 2 - 1, -1, -1):
#             tmp += nums[i]
#             max_l = max(tmp, max_l)
#         max_r = nums[len(nums) // 2]
#         tmp = 0
#         for i in range(len(nums) // 2, len(nums)):
#             tmp += nums[i]
#             max_r = max(tmp, max_r)
#         #返回三个中的最大值
#         return max(max_right,max_left,max_l+max_r)

# two-dimensional dp

## AppleCollection

In [131]:
class Solution:
    def AppleCollection(self, a: List[List]) -> int:
        m, n = len(a), len(a[0])
        if n == 0:
            raise ValueError
        else:
            dp = [[0 for _ in range(n)] for _ in range(m)]
            for i in range(n):
                dp[0][i] = sum(a[0][:i+1])
            for j in range(1, m):
                dp[j][0] = dp[j-1][0]+a[j][0]
            for i in range(1, m):
                for j in range(1, n):
                    dp[i][j] = a[i][j]+max(dp[i-1][j], dp[i][j-1])
        return dp[-1][-1]

In [132]:
a = [[10, 9, 2], [5, 3, 7], [101, 18, 1]]
s = Solution()
s.AppleCollection(a)

135

## AppleDistribution

In [217]:
sorted([1,2,3], reverse=True)

[3, 2, 1]

## UniquePaths

In [150]:
class Solution:
    def UniquePaths(self, m: int, n: int) -> int:
        dp = [[1 for _ in range(n)] for _ in range(m)]
        for i in range(1, m):
            for j in range(1, n):
                dp[i][j] = dp[i-1][j]+dp[i][j-1]
        return dp[-1][-1]

In [6]:
class Solution:
    def UniquePaths(self, m: int, n: int) -> int:
        dp = [1]+[0]*(n-1)
        for i in range(m):
            for j in range(n):
                if j >0:
                    dp[j] += dp[j-1]
        return dp[-1]

In [7]:
m = 3
n = 7
s = Solution()
s.UniquePaths(m, n)

28

In [157]:
class Solution:
    def UniquePathsObstacles(self, a: List[List]) -> int:
        m, n = len(a), len(a[0])
        dp = [1] + [0]*(n-1)
        for i in range(m):
            for j in range(n):
                if a[i][j] == 1:
                    dp[j] = 0
                elif j > 0:
                    dp[j] += dp[j-1]
        return dp[-1]

In [158]:
a = [[0, 0, 0], [0, 1, 0], [0, 0, 0]]
s = Solution()
s.UniquePathsObstacles(a)

2

In [190]:
class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        dp = [0 for _ in range(len(cost)+1)]
        for i in range(2, len(cost)+1):
            dp[i] = min(dp[i-1]+cost[i-1], dp[i-2]+cost[i-2])
        return dp[-1]

In [192]:
class Solution:
    def minCostClimbingStairs(self, cost: List[int]) -> int:
        c0, c1 = 0, 0
        for i in range(2, len(cost)+1):
            c = min(c1+cost[i-1], c0+cost[i-2])
            c0, c1 = c1, c
        return c

In [194]:
n = [1, 100, 1, 1, 1, 100, 1, 1, 100, 1]
n = [10, 15, 20]
s = Solution()
s.minCostClimbingStairs(n)

15

In [ ]:
# 给定一个非负整数 num。对于 0 ≤ i ≤ num 范围中的每个数字 i ，计算其二进制数中的 1 的数目并将它们作为数组返回

In [195]:
class Solution(object):
    def countBits(self, num: int) -> List[int]:
        res=[0]
        k=0
        for i in range(1,num+1):
            if(i == 2**k):
                res.append(1)
                k+=1
            else:
                res.append(1+res[i-2**k])
        return res

In [196]:
s = Solution()
s.countBits(5)

[0, 1, 1, 2, 1, 2]

In [ ]:
# 三角形最小路径和
# 给定一个三角形，找出自顶向下的最小路径和。每一步只能移动到下一行中相邻的结点上。

# 例如，给定三角形：

# [
#      [2],
#     [3,4],
#    [6,5,7],
#   [4,1,8,3]
# ]
# 自顶向下的最小路径和为 11（即，2 + 3 + 5 + 1 = 11）

In [ ]:
class Solution(object):
    def minimumTotal(self, triangle):
        """
        :type triangle: List[List[int]]
        :rtype: int
        """
        '''
        dp问题：利用列表进行存储，每一行每个步骤结束后的最小值，那么在最后一行，其最小值为min（4+dp[0],4+dp[1],1+dp[0],1+dp[1]...）
        所以状态转移方程为： 如果i==0 or i==len(triangle[row]) 那么其转移方程为dp[i]=dp[0]triangle[row][i]  dp[i]=dp[i-1]+triangle[row][i]
                            dp[i]=min(dp[i-1],dp[i])+triangle[row][i]
        初始值为   dp[0]=triangle[0][0]
        '''
        if len(triangle)==1:
            return triangle[0][0]
        dp=[[triangle[0][0]]]
        for i in range(1,len(triangle)):
            for j in range(len(triangle[i])):
                dp.append([])
#                 边界只有一个邻边
                if j==0:
                    dp[i].append(dp[i-1][j]+triangle[i][j])
                elif j==len(triangle[i])-1:
                    dp[i].append(dp[i-1][j-1]+triangle[i][j])
                else:
#                     当前取值，在上一层的邻边最小值相加
                    dp[i].append(min(dp[i-1][j-1],dp[i-1][j])+triangle[i][j])
        return min(dp[len(triangle)-1])

In [ ]:
# 给定一个整数数组，其中第 i 个元素代表了第 i 天的股票价格 。​

# 设计一个算法计算出最大利润。在满足以下约束条件下，你可以尽可能地完成更多的交易（多次买卖一支股票）:

# 你不能同时参与多笔交易（你必须在再次购买前出售掉之前的股票）。
# 卖出股票后，你无法在第二天买入股票 (即冷冻期为 1 天)。
# 示例:

# 输入: [1,2,3,0,2]
# 输出: 3 
# 解释: 对应的交易状态为: [买入, 卖出, 冷冻期, 买入, 卖出]

In [ ]:
# dp[i][0] = max(dp[i - 1][0], dp[i - 1][1] + prices[i])
#                  继续空仓观望       卖出手上的股票
# dp[i][1] = max(dp[i - 1][1], dp[i - 1][0] - prices[i])   # dp[i - 1][0] 不能是从 dp[i - 2][1] + prices[i] 转移过来的
#                  继续持有股票       买入股票

In [ ]:
class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        if not prices:
            return 0

        n = len(prices)
        dp = [[0, 0] for _ in range(n + 1)]
        prices.insert(0, 0)  # 下标1算第一天, 方便处理

        dp[1][1] = -prices[1]
        for i in range(2, n + 1):
            dp[i][0] = max(dp[i - 1][0], dp[i - 1][1] + prices[i])
            dp[i][1] = max(dp[i - 1][1], dp[i - 2][0] - prices[i])

        return dp[n][0]

In [ ]:
# select
#     district_name
#     ,count(*) over(partition by district_name order by district_index rows between 1 preceding and 1 following) as a
#     ,count(*) over(partition by district_name order by district_index rows between unbounded preceding and unbounded following) as b
#     ,count(*) over(partition by district_name order by district_index rows between unbounded preceding and current row) c
# from
#     dm_si.district
# ;

# LongestAscSubSequence

In [ ]:
# 给定一个无序的整数数组，找到其中最长上升子序列的长度
# 输入：[10,9,2,5,3,7,101,18]
# 输出：4 
# 解释：最长的上升子序列是 [2,3,7,101]，它的长度是 4

## greedy

In [7]:
class Solution:
    def LongestAscSubSequence(self, n: List[int]) -> int:
        size = len(n)
        if size == 0:
            raise ValueError
        else:
            x = [1]*size
            for i in range(size):
                for j in range(i):
                    if n[j] < n[i]:
                        x[i] = max(x[i], x[j]+1)
            y = max(x)
        return y

In [8]:
n = [10, 9, 2, 5, 3, 7, 101, 18]
s = Solution()
s.LongestAscSubSequence(n)

4

In [ ]:
# 时间复杂度：O(N^2)
# 空间复杂度：O(N)

## greedy with binary search

In [9]:
import numpy as np

class Solution:
    def LongestAscSubSequence(self, n: List[int]) -> int:
        x = [-np.inf]
        for i in n:
            if i > x[-1]:
                x.append(i)
            else:
                a = 0
                b = len(x)-1
                c = b
                while a <= b:
                    m = (a+b)//2
                    if x[m] >= i:
                        c = m
                        b = m-1
                    else:
                        a = m+1
                x[c] = i
        return len(x)-1

In [10]:
s = Solution()
s.LongestAscSubSequence(n)

4

In [ ]:
# n.reverse()
# n
# s.LongestAscSubSequence(n)

## greedy with bisect

In [ ]:
import numpy as np
import bisect

class Solution:
    def LongestAscSubSequence(self, n: List[int]) -> int:
        x = [-np.inf]
        for i in n:
            if i > x[-1]:
                x.append(i)
            else:
                x[bisect.bisect_left(x, i)] = i
        return len(x)-1

In [ ]:
s = Solution()
s.LongestAscSubSequence(n)

In [ ]:
# 时间复杂度：O(NlogN)
# 空间复杂度：O(N)

In [283]:
class Solution:
    def strMove(self, s: str, k: int) -> str:
        tmp = sorted(s)[:k]
        for i in tmp:
            s = s.replace(i, '')
        return s

In [284]:
s = 'bdaaefsc'
k = 3
solution = Solution()
solution.strMove(s, k)

'defsc'

In [287]:
from typing import List

class Solution:
    def intSplit(self, n: List[int], N: int) -> bool:
        size = len(n)
        result = False
        for i in range(size):
            for j in range(i, size):
                if n[i]+n[j] == N:
                    result = True
                    break
        return result

In [290]:
n = [2,3,6,8,10]
N = 15
solution = Solution()
solution.intSplit(n, N)

False

# SmallestK

In [ ]:
# 找出数组中最小的k个数，以任意顺序返回这k个数均可
# 输入：arr = [1,3,5,7,2,4,6,8], k = 4
# 输出：[1,2,3,4]

In [ ]:
import heapq
class Solution:
    def SmallestK(self, arr: List[int], k: int) -> List[int]:
        if k>len(arr) or k==0:
            return []
        heap = []
        for i in arr[:k]:
            heapq.heappush(heap, -i)
        for i in arr[k:]:
            if i < -heap[0]:
                heapq.heappop(heap)
                heapq.heappush(heap, -i)
        result = []
        for i in range(k):
            result.append(-heapq.heappop(heap))
        return result[::-1]

In [ ]:
class Solution:
    def SmallestK(self, arr: List[int], k: int) -> List[int]:
        def helper(arr, k, left, right):
            ##### 标准快速排序
            pivot = left
            low, high = left, left+1
            for high in range(left+1, right+1):
                if arr[high] < arr[pivot]:
                    low += 1
                    arr[low], arr[high] = arr[high], arr[low]
            arr[left], arr[low] = arr[low], arr[left]
            ###若当前分块长度不等于目标长度k，则根据情况进行下一步细分
            if low-left+1 < k:
                helper(arr, k-low+left-1, low+1, right)
            elif low-left+1 > k:
                helper(arr, k, left, low-1)
        
        if not arr or not k:
            return []
        helper(arr, k, 0, len(arr)-1)
        return arr[:k]

In [201]:
n = [0, 1, 2, 3, 4]
m = 3

In [198]:
n[0:m] = n[0:m][::-1]
n[m:] = n[m:][::-1]
n = n[::-1]

In [199]:
n

[3, 4, 0, 1, 2]

In [213]:
n = np.array(n)

In [214]:
n = n[list(range(m,len(n)))+list(range(0,m))]

In [215]:
n

array([3, 4, 0, 1, 2])

# MedianofOrderedArrays

In [ ]:
class Solution:
    def MedianofOrderedArrays(self, a: List[int], b: List[int]) -> int:
        m, n = len(a), len(b)
        if m > n:
            a, b, m, n = b, a, n, m
        if n == 0:
            raise ValueError
        imin, imax, half_len = 0, m, (m+n+1)//2
        while imin <= imax:
            i = (imin+imax)//2
            j = half_len-i
            if i < m and b[j-1] > a[i]:
                imin = i+1
            elif i > 0 and a[i-1] > b[j]:
                imax = i-1
            else:
                if i == 0:
                    max_of_left = b[j-1]
                elif j == 0:
                    max_of_left = a[i-1]
                else:
                    max_of_left = max(a[i-1], b[j-1])
                if (m+n) % 2 == 1:
                    return max_of_left
                if i == m:
                    min_of_right = b[j]
                elif j == n:
                    min_of_right = a[i]
                else:
                    min_of_right = min(a[i], b[j])
                return (max_of_left+min_of_right)/2

In [241]:
class Solution(object):
    def MedianofOrderedArrays(self, n1: List[int], n2: List[int]):
        l1, l2 = len(n1), len(n2)
        p1, p2 = 0, 0
        h = (l1+l2)//2
        n = []

        while p1 < l1 and p2 < l2:
            if n1[p1] < n2[p2]:
                n.append(n1[p1])
                p1 += 1
            else:
                n.append(n2[p2])
                p2 += 1

        if p1 < l1:
            n[p1+p2:] = n1[p1:]
        if p2 < l2:
            n[p1+p2:] = n2[p2:]

        if (l1+l2) % 2 == 0:
            m = (n[h-1]+n[h])/2
        else:
            m = n[h]
        return m

In [267]:
class Solution(object):
    def MedianofOrderedArrays(self, n1: List[int], n2: List[int]):
        l1, l2 = len(n1), len(n2)
        p1, p2 = 0, 0
        h = (l1+l2)//2+1
        n = []
        
        while p1 < l1 and p2 < l2:
            if n1[p1] < n2[p2]:
                n.append(n1[p1])
                p1 += 1
                if len(n)==h:
                    break
            else:
                n.append(n2[p2])
                p2 += 1
                if len(n)==h:
                    break

        if p2 >= l2:
            n[len(n):h] = n1[:h-len(n)]
        if p1 >= l1:
            n[len(n):h] = n2[:h-len(n)]

        if (l1+l2) % 2 == 0:
            m = (n[-1]+n[-2])/2
        else:
            m = n[-1]
        return n, m

In [269]:
n1 = [1, 2, 4, 6]
n2 = [5, 6, 7, 8]
# n1 = [1, 2]
# n2 = [5, 6, 7, 8]
s = Solution()
s.MedianofOrderedArrays(n1, n2)

([1, 2, 4, 5, 6], 5.5)

In [ ]:
# 给定一个字符串，找出其中不含有重复字符的 最长子串 的长度
# 输入: "abcabcbb"
# 输出: 3 
# 解释: 因为无重复字符的最长子串是 "abc"，所以其长度为 3

# EggDrop

In [ ]:
class Solution:
    def EggDrop(self, K: int, N: int) -> int:

        dp = [[i for _ in range(K + 1)] for i in range(N + 1)]

        for j in range(K + 1):
            dp[0][j] = 0

        dp[1][0] = 0
        for j in range(K + 1):
            dp[1][j] = 1

        for i in range(N + 1):
            dp[i][0] = 0
            dp[i][1] = i
        
        data = []
        for i in range(2, N + 1):
            for j in range(2, K + 1):
                for k in range(1, i + 1):
                    if i == N and j == K:
                        data.append([k, dp[k - 1][j - 1], dp[i - k][j]])
                    dp[i][j] = min(dp[i][j], max(dp[k - 1][j - 1], dp[i - k][j]) + 1)
        return dp[N][K], data

# LaplacianEigendecomposition

In [12]:
D = np.diag([1, 1, 1, 1])
W = np.array([[0, 1, 0, 0], [1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])
L = D-W

In [13]:
np.linalg.eigh(L)

(array([ 0.,  0.,  2.,  2.]),
 array([[-0.70710678, -0.        ,  0.        , -0.70710678],
        [-0.70710678, -0.        ,  0.        ,  0.70710678],
        [-0.        , -0.70710678, -0.70710678,  0.        ],
        [-0.        , -0.70710678,  0.70710678,  0.        ]]))

In [14]:
D = np.diag([11, 10, 11, 10])
W = np.array([[0, 10, 1, 0], [10, 0, 0, 0], [1, 0, 0, 10], [0, 0, 10, 0]])
L = D-W

In [15]:
np.linalg.eigh(L)

(array([  1.57692261e-15,   9.50124379e-01,   2.00000000e+01,
          2.10498756e+01]),
 array([[ 0.5       , -0.47447241,  0.5       , -0.52428611],
        [ 0.5       , -0.52428611, -0.5       ,  0.47447241],
        [ 0.5       ,  0.47447241,  0.5       ,  0.52428611],
        [ 0.5       ,  0.52428611, -0.5       , -0.47447241]]))

# pymysql

In [ ]:
from sqlalchemy.engine import create_engine

In [ ]:
engine_user = 'risk_cash_indr'
engine_pwd = '56fZGrao@ql1g0'
engine_ip = 'rm-a2d118877eu2182wt62800.mysql.ap-south-1.rds.aliyuncs.com'
engine_port = 3306
engine_db = 'strategy'
engine_charset = 'utf8'
engine = create_engine('mysql+pymysql://{}:{}@{}:{}/{}?charset={}'.format(
    engine_user, engine_pwd, engine_ip, engine_port, engine_db, engine_charset))

In [ ]:
con = engine.connect()

In [ ]:
merge.to_sql(name='cross_section', schema='data', con=con, if_exists='replace', index=False)

In [ ]:
# import pymysql
# conn = pymysql.connect(host=engine_ip,
#                        port=engine_port,
#                        user=engine_user,
#                        passwd=engine_pwd,
#                        db=engine_db, charset=engine_charset)
# cur = conn.cursor()

In [ ]:
# pd.read_sql('select * from cross_section', conn)

In [ ]:
# cur.close()